### PR TITLE
Require CakePHP 3.4

### PR DESCRIPTION
**Pull request by raul338**
Made changes to run in cakephp 3.4 / 3.5

### CODE REVIEW

**Comment by felixkempf** [comment]
Thanks for the PR. 

We ourselves don't use this plugin anymore, because we migrated to migrations and would advise to do the same, as scherersoftware/cakephp-schema just was a filler for the waiting time until migrations were usable.

Are there any reasons you still use this one, are you missing something in migrations?

**Comment by raul338** [comment]
I use migrations too for production environment.
I use this plugin to auto generate fixtures for testing purposes.

I have an AppFixture that reads schema.php and seed (from seed.php by generateseed command)

Without this plugin I would have to bake fixture after every migration and rewrite fixture seeds.
In my local testing I use a backup of production testing, for phpunit I maintain the "seed.php" file with a max of 5 records per table.

If you recommend another plugin/way to make fixture/testing easier I can try it.

**Comment by raul338** [comment]
I used this before migrations had a schema lock file
```php
<?php
namespace App\Test\Fixture;

use Cake\TestSuite\Fixture\TestFixture;
use Cake\Utility\Inflector;

/**
 * Base Fixture
 *
 */
class AppFixture extends TestFixture
{
    public $fields = [];
    public $records = [];

    /**
     * Workaround to use cakephp-schema seed as fixtures
     * @return void
     */
    public function init()
    {
        list($namespace, $className) = namespaceSplit(get_called_class());
        $className = substr($className, 0, strlen('Fixture') * -1);
        $className = Inflector::underscore($className);
        // echo "className: " . $className . "\n";

        $ret = require ROOT . DS . 'config' . DS . 'schema.php';
        if (array_key_exists($className, $ret['tables'])) {
            $this->fields = $ret['tables'][$className];
        }
        $ret = require ROOT . DS . 'config' . DS . 'seed.php';
        if (array_key_exists($className, $ret)) {
            $this->records = $ret[$className];
        }
        parent::init();
    }
}
```
And all fixtures where only a file with this conntents
```php
<?php
namespace App\Test\Fixture;

/**
 * ApartmentsFixture
 *
 */
class ApartmentsFixture extends AppFixture
{
}
```

I didn't try yet with schema-dump-default.lock, but that file is a PITA to keep in the git when multiple branches are handling different migrations in a large app.

I made this PR so I can re-use this approach in cake 3.5
I use this plugin AND cakephp/migrations together 

Also by keeping seed.php I could call `bin/cake schema drop -n && bin/cake schema load && bin/cake schema seed` and have a clean env to do debugging or to try  write controller integration testings

**Comment by felixkempf** [comment]
Thats quite clever for sure.

Thanks for the PR, I will release a new version v1.1 with your changes immediately.

**Pull request merged**
